name: Build Android APK Ultra Simple

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.4
    
    - name: Install NPM dependencies
      run: npm install
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
